GO_EASY_ON_ME = 1

include $(THEOS)/makefiles/common.mk
LIBRARY_NAME = SAFiOS910
SAFiOS910_FILES = Tweak.xm ../PSMBProgressHUD.m
SAFiOS910_FRAMEWORKS = CoreGraphics UIKit
SAFiOS910_LIBRARIES = substrate
SAFiOS910_INSTALL_PATH = /Library/Application Support/SAF

include $(THEOS_MAKE_PATH)/library.mk
