GO_EASY_ON_ME = 1

include $(THEOS)/makefiles/common.mk
LIBRARY_NAME = SAFiOS67
SAFiOS67_FILES = Tweak.xm ../PSMBProgressHUD.m
SAFiOS67_FRAMEWORKS = CoreGraphics UIKit
SAFiOS67_LIBRARIES = substrate
SAFiOS67_INSTALL_PATH = /Library/Application Support/SAF

include $(THEOS_MAKE_PATH)/library.mk
