GO_EASY_ON_ME = 1

include $(THEOS)/makefiles/common.mk
LIBRARY_NAME = SAFiOS8
SAFiOS8_FILES = Tweak.xm ../PSMBProgressHUD.m
SAFiOS8_FRAMEWORKS = CoreGraphics UIKit
SAFiOS8_LIBRARIES = substrate
SAFiOS8_INSTALL_PATH = /Library/Application Support/SAF

include $(THEOS_MAKE_PATH)/library.mk
